
ALL:Client.class Host.class Packet.class TCPend.class

Client.class:Client.java
	javac Client.java

Host.class: Host.java
	javac Host.java

Packet.class:Packet.java
	javac Packet.java

TCPend.class:TCPend.java
	javac TCPend.java

clean:
	rm -rf *.class